export const ADD_COMMENT = 'ADD_COMMENT';
export const SET_COMMENT_TEXT = 'SET_COMMENT_TEXT';
export const SET_REPLY_TEXT = 'SET_REPLY_TEXT';
export const CONSUME_YOUTUBE_VIDEO = 'CONSUME_YOUTUBE_VIDEO';
export const SET_POPUP_VIDEO = 'SET_POPUP_VIDEO';
export const RESET_VIDEO_POPUP = 'RESET_VIDEO_POPUP';
export const YOUTUBE_URL = 'https://www.youtube.com/';
export const YOUTUBE_EMBED_PATH = 'embed/';
export const YOUTUBE_URL_REGEX = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=|\?v=)([^#\&\?]*).*/;